baseURL = 'https://89095688888.ru/'
languageCode = 'ru-RU'
title = 'Юридические услуги'
uglyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmptyBundles = true

[menus]
  [[menus.main]]
    name = 'Консультация'
    pageRef = 'yuridicheskaya-konsultaciya'
    weight = 20
    
  [[menus.main]]
    name = 'Услуги'
    pageRef = 'uslugi'
    weight = 30

  [[menus.footer]]
    name = 'Политика конфиденциальности'
    url = '/privacy-policy.html'
    weight = 10

  [[menus.footer]]
    name = 'Условия использования'
    url = '/terms-of-service.html'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
